### ISSUE TITLE
Feedback Jan 17

### ISSUE THREAD

**Issue by b-g** [generative-design/generative-design-website-2#1]
@Niels-NTG Here is some quick feedback:

- [x] Please add a nicer sans-serif font
- [x] Missing old/new book landing page
- [x] Missing header section
- [x] Please ask Joey to come up with a nice intro paragraph
- [x] It would be better IMO to have a sketch images in a square format, or?
- [x] All sketch images should have a white background ... some are transparent at the moment
- [x] Missing sketch section
- [x] Please secure our email addresses, don't want to even more spam
- [x] Please add our twitter link next to our names
- [x] Please add an imprint (new page or modal or in very small in footer), use [infos](http://www.generative-gestaltung.de/contact#imprint) of the old book

**Comment by joeyklee** [comment]
@b-g is the intro paragraph for this spot here?

<img width="494" alt="screen shot 2018-01-17 at 12 51 59" src="https://user-images.githubusercontent.com/3622055/35058238-495bed9e-fb85-11e7-817d-7b576a402fb5.png">

**Comment by b-g** [comment]
Yes. But German paragraph is quite funktional speak ... English should be more friendly and doesn’t have to be a direct translation ... Thanks!

Sent while in transit

**Comment by joeyklee** [comment]
here's a few options - let me know what you think! 


## V1
Hello and welcome to Generative Design, Creative Coding on the Web. Here, you will find all of the sketches from the book and their associated code. Run the sketches directly in the browser with the p5.js-web-editor or locally on your machine by downloading the code package below. 

## V2

Hello and welcome to Generative Design, Creative Coding on the Web. Here, you will find all of the sketches from the book and their associated code. Follow the links and directions below to run the sketches directly in the browser with the p5.js-web-editor or locally on your machine. 

## V3

Generative Design, Creative Coding on the Web expands the possibility of generating new forms, visualizations, and interactions with JavaScript and P5.js. Explore the web browser as a modern canvas for creative expression by using and building on the sketches included below.

**Comment by b-g** [comment]
+1 V1

@Niels-NTG @bohnacker Which one do you prefer?

@joeyklee Many thanks!!

**Comment by bohnacker** [comment]
+1 V1

**Comment by Niels-NTG** [comment]
+1 V1

**Comment by Niels-NTG** [comment]
@b-g I've finished making the an initial version of the website. Only the old/new landing page is missing because I don't have the book cover image assets. Could you extract those from one of the design files somehow? I don't have InDesign installed on this computer.

**Comment by bohnacker** [comment]
Is the font ment to look like this? Or do I miss some dependencies?
If not, the font doesn't work with äöü... And I dont think that the font is better than the old one.
<img width="756" alt="bildschirmfoto 2018-01-26 um 10 20 34" src="https://user-images.githubusercontent.com/2828139/35433197-cc164794-0282-11e8-92cc-b10b570adb1e.png">

**Comment by b-g** [comment]
@Niels-NTG In doubt go for classic good typography open source ones: source sans, open sans, fira, lato, ibm plex

**Comment by Niels-NTG** [comment]
Despite liking the the font, I have to agree the umlaut doesn't look very good. After trying some of @b-g 's suggestions, I've landed on Source Sans Pro.

**Comment by Niels-NTG** [comment]
The landing page is done 8eceda0b8956b2b5d01bccc8d92f2af8625b3fde.

Now we have the following TODOs:

- [x] Have permanent links to an online version of each sketch. @joeyklee 
- [x] A link to the amazon.de product page and/or something else to put in the header.
- [x] New Impressum text.
- [x] Move the current website to another URL. I would propose `2009.generative-gestaltung.de` or `generative-gestaltung.de/first-edition`.
- [x] English version (only a matter of some minor find and replace).
- [x] Some SEO optimisation.
- [x] Create `@generative-gestaltung.de` mail addresses for @joeyklee and me, if possible.
- [x] Upload

**Comment by b-g** [comment]
@Niels-NTG Great!

Comments:

> A link to the amazon.de product page and/or something else to put in the header.

Not possible before the book is listed there

> New Impressum text.

Please simply update the old one. 

> Move the current website to another URL. I would propose `2009.generative-gestaltung.de` or `generative-gestaltung.de/first-edition`.

I would keep this even simpler: `generative-gestaltung.de/1` and `generative-gestaltung.de/2`

> Create `@generative-gestaltung.de` mail addresses for @joeyklee and me, if possible.

Good call, will ask Julia.

> Upload

Will send you the logins via skype

**Comment by joeyklee** [comment]
@Niels-NTG : 

> Have permanent links to an online version of each sketch. @joeyklee

I met with Cassie yesterday regarding the sketches and we should be in good shape. We haven't uploaded the sketches yet to the p5 web editor online, but all of the links should more or less look like this:

`https://editor.p5js.org/generative-design/<name_of_sketch>`

e.g.

`https://editor.p5js.org/generative-design/P_1_1_1_01`

I think you can fill those links in on the index page.
