### ISSUE TITLE
Feedback Feb 19

### ISSUE THREAD

**Issue by b-g** [generative-design/generative-design-website-2#2]
@Niels-NTG Many thanks for swift sprint to implement the website!! 🙏Nearly there. Here what I found:

**General**
- [x] Change fav icon to new book. See `/10_Social_Media/02_Profilbild`
- [x] Green color, not the one defined in layout. Please fix.
![2018-02-19 at 10 24](https://user-images.githubusercontent.com/480224/36370502-4fc10ca2-155f-11e8-984a-b2ca3ebe04fc.png)
- [x] Responsive layout. Have 4 columns on a big screen.
- [x] Please double check font sizes and font colors. Slight off. Please sync with layout.
![2018-02-19 at 10 44](https://user-images.githubusercontent.com/480224/36371330-1328d466-1562-11e8-8a29-a8b66898974e.png)

**Header**
- [x] Missing lang DE / EN switches. Please switch lang according to user's browser lang setting.
- [x] Sticky nav bar, please double check the layout. Font sizes too big. Pull menu items left. Smaller icons. ![2018-02-19 at 10 27](https://user-images.githubusercontent.com/480224/36370691-ef31ac06-155f-11e8-9ec0-deb8771fd9d1.png)
- [x] Buy the book links, fix font sizes and add a /br: "Buch kaufen /br @ Herman Schmidt Verlag"
- [x] Slideshow. The book pages are not fully visible on a big screen. Please make sure that the entire book double spread page is visible. ![2018-02-19 at 10 39](https://user-images.githubusercontent.com/480224/36371099-6bb50b8c-1561-11e8-9775-1a23d72172fc.png)
- [x] Slideshow. Please add more "new sketches" pages to the slideshow e.g. Niels and Joey sketches, emoji etc., get rid of a few old ones. Add 1 or 2 pages from the project section.

**Imprint & Contact**
- [x] Imprint section, please change
"Konzeption und Gestaltung" to "[Gold & Wirtschaftswunder](http://www.gww-design.de/), Benedikt Groß"
- [x] Imprint section, please change "Realisation" to "Web Development"
- [x] Contact section, change order to "mail all authors" /br list of all authors (I don't want go first, we should all get those emails together)

**Sketch detail view**
- [x] Missing sketch detail view. In my understanding it was originally planned that the user could use the sketches right on our website (besides the ones which just make sense on desktop e.g. tablet and emoji sketches). Or?
![webseite_i_frame](https://user-images.githubusercontent.com/480224/36370901-b308d2da-1560-11e8-8acf-284a64635b86.png)

**Comment by b-g** [comment]
And forgot ...

EN website: Please add a very prominent hint e.g. "Generative Design: Visualize, Program, and Create with JavaScript in p5.js. Will be available in October 2018 from Princeton Architectural Press! /br" before the intro paragraph. Could also be a absolute positioned sticker or banner etc. It is just important that people notice it.

**Comment by b-g** [comment]
And forgot II ... sorry for all the spam! Please add google analytics of old website.

(let me know if you guys want access)


```js
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11214833-1");
pageTracker._trackPageview();
} catch(err) {}</script>
```

**Comment by b-g** [comment]
And forgot III ... 

Please adjust the "Download code package" link to:
https://github.com/generative-design/Code-Package-p5.js/releases/latest

**Comment by b-g** [comment]
@Niels-NTG Hartmut also exported a bunch of new pages ...

GG_Preview_20-21.png
GG_Preview_26-27.png
GG_Preview_40-41.png
GG_Preview_146-147.png
GG_Preview_148-149.png
GG_Preview_180-181.png
GG_Preview_182-183.png
GG_Preview_186-187.png
GG_Preview_222-223.png

https://www.dropbox.com/s/agq0ywhk1gjsbay/GG_Preview_klein.zip?dl=0

**Comment by joeyklee** [comment]
@Niels-NTG just a quick question: so all the sketches only open on the p5 editor? No sketches are just running on their own page? (I know a little late in the game, but for some reason I thought there would be both options: 1. to view and use the sketch on the site and 2. to edit the sketch in the editor if necessary.) I might have missed that convo somewhere in the gh issues! Thanks!

**Comment by Niels-NTG** [comment]
@joeyklee I'm working on a viewer for the sketches at the moment. It's coming soon.

**Comment by joeyklee** [comment]
@Niels-NTG Ah! super. you're on top of it! 🙌

**Comment by Niels-NTG** [comment]
@b-g Could you edit those previews by Hartmut such that they look like an open book, just like https://github.com/generative-design/generative-design-website-2/blob/master/2/img/header/9783874399029_Generative-Gestaltung_Creative-Coding-im-Web10.jpg ? IMO that would look better.

**Comment by Niels-NTG** [comment]
Just added some instructions on how to edit and expand the localisation system I've build. Should be easy to expand beyond Deutsch and English if necessary in the future.

**Comment by b-g** [comment]
@Niels-NTG Thanks for the love for the website! 

Last tiny details: 

- [x] Mailto Link all authors is broken ...
- [x] Can you translate the chapter names e.g. "P.1. Farbe" to EN?
- [x] Please make the "Generative Design: Visualize, Program, and Create with JavaScript in p5.js. Will be available in October 2018 from Princeton Architectural Press!" more prominent. Red box around it etc.
